Asset.create(:ticker => "Conservative Portfolio", :price => 1, :riskiness => 1)
Asset.create(:ticker => "Balanced Portfolio", :price => 1, :riskiness => 2)
Asset.create(:ticker => "Growth Portfolio", :price => 1, :riskiness => 3)
Asset.create(:ticker => "Aggressive Portfolio", :price => 1, :riskiness => 4)
Asset.create(:ticker => "High-Growth Portfolio", :price => 1, :riskiness => 5)