Asset.create(:ticker => "CASH", :price => 1, :riskiness => 1)
Asset.create(:ticker => "BONDS", :price => 1, :riskiness => 2)
Asset.create(:ticker => "GOLD", :price => 1, :riskiness => 3)
Asset.create(:ticker => "VTI", :price => 1, :riskiness => 4)
Asset.create(:ticker => "TSLA", :price => 1, :riskiness => 5)